name: Docker Hub
on:
  push:
    branches:
      - main
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.parthkulkarni}}
          password: ${{ secrets.DOCKER_Dockerpk@2023}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ github.sha }}
      - name: Trigger Docker Hub webhook
        uses: distributhor/action-dispatch@v2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: 'docker-hub'
